import{useEffect,useMemo,useRef}from"react";import{Link,useSearchParams}from"react-router-dom";import avatarUrl from "../../../assets/teacher/teacher-emma.webp";import{LiveControls}from"../live/LiveControls";import{useLiveSession}from"../live/useLiveSession";import{lastLive,vocabularyLevel}from"../lib/runtime";import{useTeacherStore}from"../store/teacherStore";
const missions:any={hotel_checkin:{title:"飯店入住",scene:"飯店",goals:["說出訂房姓名","確認早餐時間","詢問退房時間"]},restaurant_order:{title:"餐廳點餐",scene:"餐廳",goals:["詢問推薦菜色","說明飲食限制","請服務生結帳"]},work_meeting:{title:"工作會議",scene:"工作",goals:["表達一個風險","提出替代方案","確認 action item"]},transport:{title:"問路與交通",scene:"旅遊",goals:["問目的地方向","確認月台","確認這班車是否正確"]}};
export function TeacherLivePage(){const[p]=useSearchParams(),s=useTeacherStore(),file=useRef<HTMLInputElement>(null);const mission=missions[p.get("mission")||""]||null,scene=p.get("scene")||mission?.scene||"",previous=p.get("resume")==="1"?lastLive("teacher"):null;useEffect(()=>{document.body.className="teacher-theme session-page";return()=>{document.body.className=""}},[]);
 const system=useMemo(()=>{const guidance=s.guidance==="light"?"優先保持流暢，只修正會造成誤解的錯誤。":s.guidance==="strict"?"文法、用字與不自然表達都短暫指出，給自然說法後讓學生重說一次。":"明顯錯誤時用簡短 recast 修正，不要長篇講課。";const mode=mission?"你正在帶結構化情境任務。扮演真人角色，不先給答案。逐步完成："+mission.goals.join("、")+"。":s.conversationMode==="scenario"?"使用情境角色扮演方式聊天。":s.conversationMode==="practice"?"偏向口說教練模式，多一點具體修正與重說。":"使用自然聊天模式，不要每回合都糾正。";const style=s.targetLanguage==="英文"&&s.languageStyle!=="auto"?"英文使用自然的"+(s.languageStyle==="gb"?"英國":s.languageStyle==="au"?"澳洲":"美國")+"當代日常口音與措辭。":"";return"你是 Crew Teacher 的真人感語言老師 Emma。目標語言："+s.targetLanguage+"。學生推估程度："+vocabularyLevel()+"。"+(scene?"目前情境："+scene+"。":"")+mode+guidance+style+"以目標語言為主，學生卡住時才用繁中短解釋。一次 1-3 句。"},[mission,scene,s]);
 const opening=previous?.turns?.length?"以下是上次最後幾輪，請自然接著聊，不重新自我介紹：\n"+previous.turns.slice(-4).map((t:any)=>[t.input?"學生："+t.input:"",t.output?"老師："+t.output:""].filter(Boolean).join("\n")).join("\n"):mission?"直接進入「"+mission.title+"」角色扮演，你先以真人角色開口。":"現在開始一對一練習。請自然開口問我第一個短問題。";
 const live=useLiveSession({pageKey:"teacher",title:(mission?.title||scene||"口說練習")+" · "+s.targetLanguage,system,openingPrompt:opening,voice:s.voice,language:s.targetLanguage,teacherReport:true});
 return <><header className="app-header"><div className="shell inner"><div className="app-brand"><Link className="back-btn" to="/teacher/practice">‹</Link><div className="app-title"><strong>Emma</strong><small>Crew Teacher</small></div></div><span className="status connected"><i className="status-dot"/><span>{live.state==="speaking"?"老師說話中":live.state==="listening"?"正在聽你說":"語音練習"}</span></span></div></header><main className="session-shell"><section className="session-person"><div className="avatar"><img src={avatarUrl} alt="Emma"/></div><h1>{mission?.title||"Emma 老師"}</h1><p>{mission?"完成任務即可，不必背整段對話。":"直接說就好，我會先開口。"}</p></section>{mission&&<div className="notice"><div><b>情境任務</b><p>{mission.goals.join(" · ")}</p></div><span className="pill">任務模式</span></div>}
 <section className="live-stage" data-state={live.state}><h2 className="live-title">{mission?mission.title:"1 對 1 語言練習"}</h2><div className="live-orb"><span>E</span></div><LiveControls live={live}/>
 <div className="live-presets"><button onClick={()=>live.sendText("換一個更生活化的話題，直接問我一個短問題。")}>換話題</button><button onClick={()=>live.sendText("請糾正我剛剛最明顯的一個錯誤，給我自然說法後讓我重說一次。")}>糾正我</button><button onClick={()=>live.sendText("現在進入角色扮演，請扮演情境裡的真人角色。")}>角色扮演</button><button onClick={()=>live.sendText("請把接下來的語速稍微放慢，但保持自然發音。")}>說慢一點</button></div>
 <details className="live-settings"><summary>快捷設定</summary><div className="live-setup-grid"><label><span className="label">目標語言</span><select className="field" value={s.targetLanguage} onChange={e=>s.setTargetLanguage(e.target.value)}><option>英文</option><option>日文</option><option>韓文</option><option>西班牙文</option><option>法文</option></select></label><label><span className="label">聊天模式</span><select className="field" value={s.conversationMode} onChange={e=>s.setConversationMode(e.target.value as any)}><option value="natural">自然聊天</option><option value="scenario">情境聊天</option><option value="practice">練習聊天</option></select></label><label><span className="label">練習方式</span><select className="field" value={s.guidance} onChange={e=>s.setGuidance(e.target.value as any)}><option value="light">輕度引導</option><option value="normal">適時修正</option><option value="strict">積極糾正</option></select></label><label><span className="label">老師音色</span><select className="field" value={s.voice} onChange={e=>s.setVoice(e.target.value)}><option>Kore</option><option>Aoede</option><option>Puck</option><option>Charon</option><option>Fenrir</option></select></label></div></details>
 <div className="vision-box"><div className="vision-head"><strong>讓 Emma 看一張圖</strong><span>教材 · 題目 · 菜單 · 路牌</span></div><div className="vision-actions"><button className="vision-btn" disabled={live.state!=="listening"} onClick={()=>file.current?.click()}>選圖片</button></div><input ref={file} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void live.sendImageFile(f,"請先真的看圖，再以目前目標語言帶我學。先問我一個和圖片直接相關的問題。");e.currentTarget.value=""}}/></div>
 <div className="live-transcript"><div className={"live-line user "+(live.input?"show":"")}><small>你剛剛說</small><span>{live.input}</span></div><div className={"live-line "+(live.output?"show":"")}><small>Emma</small><span>{live.output}</span></div></div></section>
 {live.report&&<section className="report-card"><div className="row" style={{justifyContent:"space-between"}}><div><span className="kicker">Session Report</span><h3>課後學習報告</h3></div><div className="report-score">{String(live.report.overall_score??"--")}</div></div><div className="report-grid"><div className="report-stat"><b>{String(live.report.fluency_score??"--")}</b><span>流暢度</span></div><div className="report-stat"><b>{String(live.report.vocab_score??"--")}</b><span>詞彙</span></div><div className="report-stat"><b>{String(live.report.grammar_score??"--")}</b><span>文法</span></div></div><div className="report-body">{String(live.report.summary??"")}</div></section>}</main></>}
