export type ReadingPassage={id:string;title:string;text:string;source:string;level:string;seconds:number;focus:string;category:string};
export const CLASSIC_READING_LIBRARY:ReadingPassage[]=[
{id:"classic_aesop_north_wind",title:"The North Wind and the Sun",text:"The North Wind and the Sun once argued about which of them was stronger. They agreed to test their power on a traveler walking along the road. The wind blew harder and harder, but the traveler only wrapped his coat more tightly around himself. Then the sun shone gently and warmly. Before long, the traveler became hot and took off his coat. Quiet warmth had succeeded where force had failed.",source:"Aesop · adapted",level:"Easy",seconds:55,focus:"word endings · sentence stress",category:"Classic"},
{id:"classic_aesop_lion_mouse",title:"The Lion and the Mouse",text:"A lion once caught a tiny mouse beneath his paw. The mouse begged to be released and promised that one day he might return the favor. The lion laughed at the idea, but let him go. Later, hunters trapped the lion in a strong net. Hearing his roar, the mouse hurried over and chewed through the ropes. The lion learned that help can come from the smallest and most unexpected friend.",source:"Aesop · adapted",level:"Easy",seconds:55,focus:"past tense endings · clear consonants",category:"Classic"},
{id:"classic_aesop_tortoise_hare",title:"The Tortoise and the Hare",text:"A fast hare often laughed at a tortoise for moving so slowly. Tired of the teasing, the tortoise challenged him to a race. The hare quickly ran far ahead and decided he had plenty of time to rest. While he slept, the tortoise kept moving at the same steady pace. By the time the hare woke up, the tortoise was already near the finish line. Steady effort had beaten careless confidence.",source:"Aesop · adapted",level:"Easy",seconds:55,focus:"rhythm · long and short vowels",category:"Classic"},
{id:"classic_franklin_whistle",title:"Too Much for the Whistle",text:"As a child, Benjamin Franklin once saw another boy with a whistle and wanted it badly. He offered all the coins in his pocket without asking what the whistle was really worth. When he returned home, his family laughed because he had paid far too much. Years later, Franklin remembered the lesson whenever he saw people giving up too much time, peace, or freedom for something of little value.",source:"Benjamin Franklin · adapted",level:"Normal",seconds:60,focus:"linking · contrast stress",category:"Classic"},
{id:"classic_sherlock_observation",title:"The Power of Observation",text:"Sherlock Holmes often amazed people by noticing details they had ignored. A worn sleeve, a spot of mud, or a small mark on a watch could suggest an entire story. His talent did not depend on magic. It came from careful attention, patient comparison, and the habit of asking what each clue might mean. The lesson is simple: when we slow down and truly observe, ordinary things can reveal far more than we expect.",source:"Sherlock Holmes · inspired adaptation",level:"Normal",seconds:60,focus:"consonant clusters · intonation",category:"Classic"},
{id:"classic_alice_rabbit_hole",title:"Down the Rabbit Hole",text:"Alice was sitting beside her sister when a white rabbit suddenly hurried past. Seeing a rabbit was not unusual, but this one wore a waistcoat and checked a pocket watch. Curious, Alice followed it across the field and watched it disappear into a deep rabbit hole. Without taking time to consider what might happen next, she climbed in after it. That single decision carried her away from an ordinary afternoon and into a world of impossible surprises.",source:"Alice in Wonderland · adapted",level:"Normal",seconds:65,focus:"sentence rhythm · weak forms",category:"Classic"},
{id:"classic_secret_garden",title:"The Hidden Garden",text:"Behind an old wall stood a garden that had been locked and forgotten for years. Its paths were buried under leaves, and its roses had grown wild. When a curious child finally found the hidden key, the garden slowly came back to life. New leaves appeared, flowers opened, and the quiet place became full of color again. Caring for the garden also changed the people who entered it, reminding them that neglected things can sometimes bloom again.",source:"The Secret Garden · adapted",level:"Normal",seconds:65,focus:"connected speech · voiced endings",category:"Classic"},
{id:"classic_twain_river",title:"Life Along the River",text:"A wide river can seem peaceful from the shore, but people who work on it learn to read every bend and current. A pilot watches the color of the water, the shape of the banks, and the position of distant trees. Small changes can warn of shallow ground or a hidden obstacle. Over time, the river becomes like a book written in moving water. Experience turns what first looks ordinary into a landscape full of meaning.",source:"Mark Twain · inspired adaptation",level:"Challenge",seconds:65,focus:"r sounds · phrasing · emphasis",category:"Classic"}
];
