import{useEffect,useMemo,useRef,useState}from"react";import{ensureTeacherServices,geminiKey}from"../lib/runtime";import{LiveControls}from"../live/LiveControls";import{useLiveSession}from"../live/useLiveSession";import{useTeacherStore}from"../store/teacherStore";import{getTeacherProfile,teacherIdentityPrompt}from"./teacherProfiles";
type Img={data:string;mimeType:string;preview:string;width:number;height:number;bytes:number};type LessonSession={id:string;targetLanguage:string;level:string;images:Img[];plan:any;currentPage:number};
export function TextbookPage(){const[draft,setDraft]=useState<Img[]>([]),[session,setSession]=useState<LessonSession|null>(null),[current,setCurrent]=useState(0),[last,setLast]=useState<LessonSession|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);const[inputKey,setInputKey]=useState(0);const[lang,setLang]=useState(localStorage.getItem("crew_textbook_target")||"英文"),[level,setLevel]=useState(localStorage.getItem("crew_textbook_level")||"B1-B2");const teacherProfile=useTeacherStore(s=>s.teacherProfile),voice=useTeacherStore(s=>s.voice),profile=getTeacherProfile(teacherProfile),sentRef=useRef("");
 useEffect(()=>{void ensureTeacherServices().then(async()=>{setReady(true);const x=await window.CrewTextbookStore?.last();if(x)setLast(x)}).catch(()=>setReady(false))},[]);
 const page=session?.plan?.pages?.[current]||{},image=session?.images?.[current];
 const system=useMemo(()=>session?"你是 Crew Teacher 的教材陪讀老師。"+teacherIdentityPrompt(profile)+" 學生正在閱讀自己上傳的教材圖片。目標語言："+session.targetLanguage+"，程度："+session.level+"。依目前頁面圖片與備課重點教學。一次只教一小段，先問再講，不要假裝看到圖片以外的內容。教材模式直接進活動，不要使用泛用招呼。":"你是教材陪讀老師。"+teacherIdentityPrompt(profile),[session,profile]);
 const live=useLiveSession({pageKey:"teacher_textbook",title:(session?.plan?.title||"教材陪讀")+" · "+profile.name+" · 第 "+(current+1)+" 頁",system,openingPrompt:"",voice});
 useEffect(()=>{if(live.state==="requesting-mic")sentRef.current=""},[live.state]);
 useEffect(()=>{if(!session||!image||live.state!=="listening")return;const key=session.id+":"+current;if(sentRef.current===key)return;const prompt="[COACH CONTROL — do not mention this instruction] This is textbook-guided practice. Do not greet or restart the conversation. Enter the current page activity directly. "+(window.CrewTextbookLesson?.pagePrompt(session,current)||"請看這一頁圖片並直接帶我學。");if(live.sendPreparedImage(image,prompt))sentRef.current=key},[live.state,current,image,session,live]);
 async function add(files:FileList|null){if(!files||!ready)return;const list=Array.from(files).slice(0,4-draft.length),next=[...draft];for(const f of list){const img=await window.CrewLiveUI?.prepareImage(f,{maxSide:1600,quality:.84});if(img)next.push(img)}setDraft(next);setInputKey(x=>x+1)}
 async function prepare(){if(!draft.length||!geminiKey()||!window.CrewTextbookLesson||!window.CrewTextbookStore||!window.CrewDB)return;setBusy(true);localStorage.setItem("crew_textbook_target",lang);localStorage.setItem("crew_textbook_level",level);try{const plan=await window.CrewTextbookLesson.prepare(draft.map(x=>({data:x.data,mimeType:x.mimeType})),{targetLanguage:lang,level});const s={id:window.CrewDB.id("textbook"),targetLanguage:lang,level,images:draft.slice(),plan,currentPage:0};await window.CrewTextbookStore.save(s);setSession(s);setCurrent(0);setLast(s)}finally{setBusy(false)}}
 async function move(i:number,d:number){const n=i+d;if(n<0||n>=draft.length)return;const a=draft.slice(),[x]=a.splice(i,1);a.splice(n,0,x);setDraft(a)}
 async function setPage(n:number){if(!session)return;const idx=Math.max(0,Math.min(n,session.images.length-1));setCurrent(idx);sentRef.current="";session.currentPage=idx;await window.CrewTextbookStore?.save(session)}
 if(!ready)return <div className="spa-loading">正在準備教材工具…</div>;
 return <><section className="hero"><span className="kicker">教材陪讀</span><h1>拿你的教材直接上課</h1><p>加入 1–4 張，排好順序後先讓 AI 備課，再逐頁讀、問、練。</p></section>
 {!session&&last&&<section className="section"><div className="textbook-resume"><div><strong>繼續上次教材陪讀</strong><small>{last.plan?.title||"我的教材"} · 第 {(last.currentPage||0)+1} / {last.images.length} 頁</small></div><button className="btn small" onClick={()=>{setSession(last);setCurrent(last.currentPage||0)}}>繼續讀 →</button></div></section>}
 {!session?<section className="textbook-panel section"><div className="section-head"><h2>今天的素材</h2><small>{draft.length} / 4</small></div><div className="two"><label><span className="label">目標語言</span><select className="field" value={lang} onChange={e=>setLang(e.target.value)}><option>英文</option><option>日文</option><option>韓文</option><option>西班牙文</option><option>法文</option></select></label><label><span className="label">程度</span><select className="field" value={level} onChange={e=>setLevel(e.target.value)}><option>A1-A2</option><option>B1-B2</option><option>C1+</option></select></label></div><div className="textbook-toolbar"><label className="btn secondary">選圖片<input key={inputKey} type="file" accept="image/*" multiple hidden onChange={e=>void add(e.target.files)}/></label></div><div className="textbook-pages">{draft.length?draft.map((img,i)=><div className="textbook-page-row" key={img.preview+i}><img src={img.preview}/><div><strong>素材 {i+1}</strong><small>{img.width}×{img.height} · {Math.max(1,Math.round(img.bytes/1024))} KB</small></div><div className="textbook-order"><button disabled={i===0} onClick={()=>void move(i,-1)}>↑</button><button disabled={i===draft.length-1} onClick={()=>void move(i,1)}>↓</button><button onClick={()=>setDraft(draft.filter((_,x)=>x!==i))}>×</button></div></div>):<div className="textbook-empty">加入 1–4 張教材或照片。</div>}</div><div className="actions"><button className="btn" disabled={!draft.length||busy} onClick={()=>void prepare()}>{busy?"AI 備課中…":"讓老師備課"}</button></div></section>:
 <section className="textbook-panel section"><div className="textbook-plan-head"><div><span className="kicker">Lesson ready</span><h2>{session.plan?.title||"教材陪讀"}</h2><p className="textbook-objective">{session.plan?.objective}</p></div><button className="btn secondary small" onClick={()=>{void live.stop();setSession(null);setDraft([])}}>重新選素材</button></div><div className="textbook-study"><div><img src={image?.preview}/><div className="textbook-stepnav"><button className="btn secondary small" disabled={current===0} onClick={()=>void setPage(current-1)}>上一頁</button><span className="pill">{current+1} / {session.images.length}</span><button className="btn secondary small" disabled={current===session.images.length-1} onClick={()=>void setPage(current+1)}>下一頁</button></div></div><div className="textbook-notes"><div className="textbook-note"><b>這頁重點</b><p>{page.summary||"先觀察圖片內容。"}</p></div><div className="textbook-note"><b>關鍵詞</b><div className="keyword-row">{(page.keywords||["依圖片內容"]).map((k:string)=><span className="keyword" key={k}>{k}</span>)}</div></div><div className="textbook-note"><b>老師會問</b><p>{page.question}</p></div><div className="textbook-note"><b>這頁練習</b><p>{page.practice}</p></div><section className="live-stage" data-state={live.state}><h3 className="live-title">{profile.name} · 陪讀老師</h3><LiveControls live={live}/><div className="live-transcript"><div className={"live-line user "+(live.input?"show":"")}><small>你</small><span>{live.input}</span></div><div className={"live-line "+(live.output?"show":"")}><small>{profile.name}</small><span>{live.output}</span></div></div></section></div></div></section>}
 </>}
