import{useEffect,useState}from"react";import{Link}from"react-router-dom";import{ensureStoryServices}from"../lib/runtime";
const LANGS=[["zh-TW","繁體中文"],["en","English"],["ja","日本語"],["ko","한국어"],["fr","Français"],["de","Deutsch"],["es","Español"]];
const VOICES=["Leda","Kore","Aoede","Puck","Charon","Fenrir"];
export function StoryMyPage(){
 const[count,setCount]=useState(0),[language,setLanguage]=useState(localStorage.getItem("crew_story_language")||"zh-TW"),[voice,setVoice]=useState(localStorage.getItem("crew_story_voice")||"Leda"),[style,setStyle]=useState(localStorage.getItem("crew_story_style")||"bedtime");
 useEffect(()=>{void ensureStoryServices().then(async()=>setCount((await window.CrewStoryStore!.list()).length))},[]);
 const save=(key:string,value:string,set:(v:string)=>void)=>{localStorage.setItem("crew_story_"+key,value);set(value)};
 return <><section className="hero"><span className="kicker">My Story</span><h1>我的 Story</h1><p>管理故事偏好、說書語言、聲線與 AI 設定；和 APK 的「我的」頁保持同一個產品概念。</p></section>
 <section className="section"><div className="teacher-stats"><div><strong>{count}</strong><span>我的故事</span></div><div><strong>3</strong><span>內建故事</span></div><div><strong>{language}</strong><span>說書語言</span></div></div></section>
 <section className="section panel"><div className="section-head"><h2>故事偏好</h2><small>會套用到新 Live session</small></div><label className="label">說書語言</label><select className="field" value={language} onChange={e=>save("language",e.target.value,setLanguage)}>{LANGS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><label className="label">阿奇聲線</label><select className="field" value={voice} onChange={e=>save("voice",e.target.value,setVoice)}>{VOICES.map(x=><option key={x} value={x}>{x}</option>)}</select><label className="label">預設故事風格</label><select className="field" value={style} onChange={e=>save("style",e.target.value,setStyle)}><option value="bedtime">睡前</option><option value="adventure">冒險</option><option value="fable">寓言</option><option value="scifi">科幻</option><option value="emotional">溫暖情感</option></select></section>
 <section className="section panel"><div className="section-head"><h2>AI 與進階</h2></div><Link className="list-item" to="/settings"><div><strong>Gemini API Key</strong><small>故事創作、實體書辨識與 Live 都使用同一個 BYOK key。</small></div><span>›</span></Link><div className="notice" style={{marginTop:12}}><div><b>關於照片與語音</b><p>只上傳你願意送到已設定 AI 服務的照片、語音與故事內容。</p></div></div></section></>
}