import{useEffect,useRef,useState}from"react";import{clearGeminiKey,ensureLive,geminiKey,saveGeminiKey}from"../lib/runtime";
function uiMessage(value:unknown){return String(value||"語音連線發生問題").replace(/gemini-[0-9A-Za-z.-]+/gi,"語音服務")}
export function SettingsPage(){
 const[key,setKey]=useState(geminiKey()),[remember,setRemember]=useState(Boolean(localStorage.getItem("crew_gemini_api_key"))),[status,setStatus]=useState("尚未測試。");
 const[testing,setTesting]=useState(false),[volume,setVolume]=useState(Number(localStorage.getItem("crew_live_volume")||100));const liveRef=useRef<any>(null);
 const caps=[["麥克風",!!navigator.mediaDevices?.getUserMedia],["WebSocket",typeof WebSocket!=="undefined"],["Web Audio",!!(window.AudioContext||(window as any).webkitAudioContext)],["Wake Lock",!!(navigator as any).wakeLock?.request]];
 useEffect(()=>()=>{if(liveRef.current)void liveRef.current.stop({silentStatus:true,emitTerminal:false})},[]);
 async function test(){
  if(!key.trim()){setStatus("先貼上 API key");return}setTesting(true);saveGeminiKey(key,remember);setStatus("正在測試語音連線…");
  try{await ensureLive();if(!window.CrewLive)throw new Error("Live runtime 未載入");
   const session=new window.CrewLive.Session({system:"這是語音連線測試。請只用繁體中文說一句「連線成功」，不要延伸聊天。",openingPrompt:"請現在說出測試句。",voice:"Kore",volume,manualInterruptOnly:true,maxLiveAttempts:2,connectTimeoutMs:8000,replyTimeoutMs:10000,onStatus:v=>setStatus(uiMessage(v)),onTurnComplete:async(turn:any)=>{if(!turn.hasValidOutput)return;await session.waitForPlaybackDrain(6500);await session.stop({reason:"test-complete",silentStatus:true,emitTerminal:false,emitState:false});liveRef.current=null;setStatus("語音連線成功。");setTesting(false)},onError:(e:Error)=>{setStatus("語音測試失敗："+uiMessage(e.message));setTesting(false)}});liveRef.current=session;await session.start();
  }catch(e){liveRef.current=null;setStatus("語音測試失敗："+uiMessage(e instanceof Error?e.message:e));setTesting(false)}
 }
 return <><section className="hero"><span className="kicker">設定</span><h1>Gemini 設定</h1><p>設定一次，Teacher、Story、Fortune 共用。</p></section>
 <section className="section panel"><h3>第一次設定</h3><p className="meta">Story 的故事創作、實體書陪讀與 AI 功能需要 Key；Fortune 的命盤計算與基本結果不需要 Key，只有 AI 解讀與老師對話需要。</p><div className="setup-steps"><div className="step"><b>1</b><span><strong>開啟 Google AI Studio</strong><small>使用自己的 Google 帳戶登入。</small></span></div><div className="step"><b>2</b><span><strong>Create API key</strong><small>建立 Gemini API key 並複製。</small></span></div><div className="step"><b>3</b><span><strong>回到 Crew 貼上</strong><small>儲存後三個產品共用。</small></span></div></div>
 <div className="actions"><a className="btn secondary" href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">開啟 Google AI Studio</a></div>
 <label className="label">Gemini API key</label><input className="field" type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="貼上 API key"/>
 <p className="meta" style={{marginTop:8}}>Key 只會保存在這個瀏覽器的本機或工作階段儲存空間；請勿分享給其他人，用量與可能費用由你的 Google 專案管理。</p><label className="row" style={{marginTop:10}}><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span className="meta">記住在這台裝置</span></label>
 <div className="actions"><button className="btn" onClick={()=>{if(!key.trim()){setStatus("先貼上 API key");return}saveGeminiKey(key,remember);setStatus("已儲存。")}}>儲存 Key</button><button className="btn secondary" disabled={testing} onClick={()=>void test()}>{testing?"測試中…":"測試語音"}</button><button className="btn danger" onClick={()=>{if(liveRef.current)void liveRef.current.stop({silentStatus:true,emitTerminal:false});liveRef.current=null;clearGeminiKey();setKey("");setRemember(false);setStatus("已清除。")}}>清除 key</button></div><div className="result">{status}</div></section>
 <section className="section panel"><div className="section-head"><h2>語音體驗</h2><small>共用設定</small></div><div><label className="label">預設播放音量</label><div className="range-row"><input className="field" type="range" min="0" max="100" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);localStorage.setItem("crew_live_volume",String(v))}}/><strong>{volume}%</strong></div></div><details className="settings-diagnostics"><summary>瀏覽器診斷</summary><p className="meta">只有語音連線異常時才需要查看。</p><div className="result settings-capabilities">{caps.map(([n,ok])=><div key={String(n)}>{ok?"✓ ":"— "}{String(n)}</div>)}</div></details><div className="actions"><button className="btn danger" onClick={()=>{["teacher","story","fortune","teacher_pronunciation","teacher_textbook"].forEach(n=>{localStorage.removeItem("crew_history_"+n);localStorage.removeItem("crew_live_last_"+n)});setStatus("已清除語音紀錄。")}}>清除語音紀錄</button></div></section></>;
}
